schemaName: sharding_db
dataSources:
  ds_0:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 260
    minPoolSize: 10
    password: Enmo@123
    url: jdbc:opengauss://127.0.0.1:15432/test?batchMode=on
    username: gaussdb
  ds_1:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 260
    minPoolSize: 10
    password: Enmo@123
    url: jdbc:opengauss://127.0.0.1:15433/test?batchMode=on
    username: gaussdb
rules:
  - !SHARDING
    defaultDatabaseStrategy:
      none: null
    defaultTableStrategy:
      none: null
    shardingAlgorithms:
      ds_count_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${id % 2}
      t_account_inline:
        type: INLINE
        props:
          algorithm-expression: account_${id % 2}
    tables:
      account:
        actualDataNodes: ds_${0..1}.account_${0..1}
        databaseStrategy:
          standard:
            shardingAlgorithmName: ds_count_inline
            shardingColumn: id
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: t_account_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123